services:
  web:
    build: .
    restart: always
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia  # Para versiones antiguas de Docker
